services:
  - type: web
    name: fallout-nova-scotia-gm
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_VOLUME_PATH
        value: /var/data
      - key: PERIODIC_SAVE_MS
        value: "60000"
      - key: SAVE_BACKUP_LIMIT
        value: "20"
    disk:
      name: fallout-data
      mountPath: /var/data
      sizeGB: 1
